
####################################################################################
# Generated by Vivado 2023.2 built on 'Fri Oct 13 20:14:34 MDT 2023' by 'xbuild'
# Command Used: ::write_xdc -force {C:/Users/Arturo/Documents/fpga/VivadoMCP-TCL/Vivado TCL MCP/vivado-mcp-socket/.tmp/mcp_test_constraints_default.xdc}
####################################################################################


# User Generated miscellaneous constraints 

make_diff_pair_ports f_si_a_clk3_p f_si_a_clk3_n

####################################################################################
# Constraints from file : 'ctrl_ddr.xdc'
####################################################################################

##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  Mon Mar  9 15:46:00 2026

##  Generated by MIG Version 4.2
##
##################################################################################################
##  File name :       ctrl_ddr.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K160T-FFG676
##                    Speedgrade:        -3
##                    Design Entry:      VHDL
##                    Frequency:         500 MHz
##                    Time Period:       2000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-107
## Data Width: 16
## Time Period: 2000
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_p[0]}]

#create_clock -period 5 [get_ports c0_sys_clk_i]

#create_clock -period 5 [get_ports clk_ref_i]

############## NET - IOSTANDARD ##################


# PadFunction: IO_L5P_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[0]}]
set_property PACKAGE_PIN AF19 [get_ports {c0_ddr3_dq[0]}]

# PadFunction: IO_L5N_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[1]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[1]}]
set_property PACKAGE_PIN AF20 [get_ports {c0_ddr3_dq[1]}]

# PadFunction: IO_L4P_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[2]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[2]}]
set_property PACKAGE_PIN AD15 [get_ports {c0_ddr3_dq[2]}]

# PadFunction: IO_L1P_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[3]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[3]}]
set_property PACKAGE_PIN AE17 [get_ports {c0_ddr3_dq[3]}]

# PadFunction: IO_L2P_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[4]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[4]}]
set_property PACKAGE_PIN AF14 [get_ports {c0_ddr3_dq[4]}]

# PadFunction: IO_L2N_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[5]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[5]}]
set_property PACKAGE_PIN AF15 [get_ports {c0_ddr3_dq[5]}]

# PadFunction: IO_L4N_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[6]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[6]}]
set_property PACKAGE_PIN AE15 [get_ports {c0_ddr3_dq[6]}]

# PadFunction: IO_L1N_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[7]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[7]}]
set_property PACKAGE_PIN AF17 [get_ports {c0_ddr3_dq[7]}]

# PadFunction: IO_L17P_T2_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[8]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[8]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[8]}]
set_property PACKAGE_PIN AC19 [get_ports {c0_ddr3_dq[8]}]

# PadFunction: IO_L17N_T2_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[9]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[9]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[9]}]
set_property PACKAGE_PIN AD19 [get_ports {c0_ddr3_dq[9]}]

# PadFunction: IO_L16P_T2_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[10]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[10]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[10]}]
set_property PACKAGE_PIN AA19 [get_ports {c0_ddr3_dq[10]}]

# PadFunction: IO_L16N_T2_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[11]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[11]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[11]}]
set_property PACKAGE_PIN AA20 [get_ports {c0_ddr3_dq[11]}]

# PadFunction: IO_L14P_T2_SRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[12]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[12]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[12]}]
set_property PACKAGE_PIN AB17 [get_ports {c0_ddr3_dq[12]}]

# PadFunction: IO_L14N_T2_SRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[13]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[13]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[13]}]
set_property PACKAGE_PIN AC17 [get_ports {c0_ddr3_dq[13]}]

# PadFunction: IO_L13P_T2_MRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[14]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[14]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[14]}]
set_property PACKAGE_PIN AC18 [get_ports {c0_ddr3_dq[14]}]

# PadFunction: IO_L13N_T2_MRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dq[15]}]
set_property SLEW FAST [get_ports {c0_ddr3_dq[15]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c0_ddr3_dq[15]}]
set_property PACKAGE_PIN AD18 [get_ports {c0_ddr3_dq[15]}]

# PadFunction: IO_L19P_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[12]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[12]}]
set_property PACKAGE_PIN Y17 [get_ports {c0_ddr3_addr[12]}]

# PadFunction: IO_L21N_T3_DQS_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[11]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[11]}]
set_property PACKAGE_PIN W19 [get_ports {c0_ddr3_addr[11]}]

# PadFunction: IO_L21P_T3_DQS_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[10]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[10]}]
set_property PACKAGE_PIN W18 [get_ports {c0_ddr3_addr[10]}]

# PadFunction: IO_L22N_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[9]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[9]}]
set_property PACKAGE_PIN W16 [get_ports {c0_ddr3_addr[9]}]

# PadFunction: IO_L22P_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[8]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[8]}]
set_property PACKAGE_PIN W15 [get_ports {c0_ddr3_addr[8]}]

# PadFunction: IO_L23N_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[7]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[7]}]
set_property PACKAGE_PIN V19 [get_ports {c0_ddr3_addr[7]}]

# PadFunction: IO_L23P_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[6]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[6]}]
set_property PACKAGE_PIN V18 [get_ports {c0_ddr3_addr[6]}]

# PadFunction: IO_L24N_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[5]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[5]}]
set_property PACKAGE_PIN W14 [get_ports {c0_ddr3_addr[5]}]

# PadFunction: IO_L24P_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[4]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[4]}]
set_property PACKAGE_PIN V14 [get_ports {c0_ddr3_addr[4]}]

# PadFunction: IO_L7N_T1_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[3]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[3]}]
set_property PACKAGE_PIN AA15 [get_ports {c0_ddr3_addr[3]}]

# PadFunction: IO_L7P_T1_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[2]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[2]}]
set_property PACKAGE_PIN AA14 [get_ports {c0_ddr3_addr[2]}]

# PadFunction: IO_L8N_T1_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[1]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[1]}]
set_property PACKAGE_PIN AD14 [get_ports {c0_ddr3_addr[1]}]

# PadFunction: IO_L8P_T1_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_addr[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[0]}]
set_property PACKAGE_PIN AC14 [get_ports {c0_ddr3_addr[0]}]

# PadFunction: IO_L10P_T1_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_ba[2]}]
set_property SLEW FAST [get_ports {c0_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[2]}]
set_property PACKAGE_PIN AB14 [get_ports {c0_ddr3_ba[2]}]

# PadFunction: IO_L11N_T1_SRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_ba[1]}]
set_property SLEW FAST [get_ports {c0_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[1]}]
set_property PACKAGE_PIN AA18 [get_ports {c0_ddr3_ba[1]}]

# PadFunction: IO_L11P_T1_SRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_ba[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[0]}]
set_property PACKAGE_PIN AA17 [get_ports {c0_ddr3_ba[0]}]

# PadFunction: IO_L9N_T1_DQS_32
set_property VCCAUX_IO NORMAL [get_ports c0_ddr3_ras_n]
set_property SLEW FAST [get_ports c0_ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports c0_ddr3_ras_n]
set_property PACKAGE_PIN Y16 [get_ports c0_ddr3_ras_n]

# PadFunction: IO_L9P_T1_DQS_32
set_property VCCAUX_IO NORMAL [get_ports c0_ddr3_cas_n]
set_property SLEW FAST [get_ports c0_ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports c0_ddr3_cas_n]
set_property PACKAGE_PIN Y15 [get_ports c0_ddr3_cas_n]

# PadFunction: IO_L10N_T1_32
set_property VCCAUX_IO NORMAL [get_ports c0_ddr3_we_n]
set_property SLEW FAST [get_ports c0_ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports c0_ddr3_we_n]
set_property PACKAGE_PIN AB15 [get_ports c0_ddr3_we_n]

# PadFunction: IO_L18N_T2_32
set_property VCCAUX_IO NORMAL [get_ports c0_ddr3_reset_n]
set_property SLEW FAST [get_ports c0_ddr3_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports c0_ddr3_reset_n]
set_property PACKAGE_PIN AB20 [get_ports c0_ddr3_reset_n]

# PadFunction: IO_25_VRP_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_cke[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_cke[0]}]
set_property PACKAGE_PIN W13 [get_ports {c0_ddr3_cke[0]}]

# PadFunction: IO_L12P_T1_MRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_odt[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_odt[0]}]
set_property PACKAGE_PIN AB16 [get_ports {c0_ddr3_odt[0]}]

# PadFunction: IO_L12N_T1_MRCC_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_cs_n[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_cs_n[0]}]
set_property PACKAGE_PIN AC16 [get_ports {c0_ddr3_cs_n[0]}]

# PadFunction: IO_L6P_T0_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dm[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[0]}]
set_property PACKAGE_PIN AD16 [get_ports {c0_ddr3_dm[0]}]

# PadFunction: IO_L18P_T2_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dm[1]}]
set_property SLEW FAST [get_ports {c0_ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[1]}]
set_property PACKAGE_PIN AB19 [get_ports {c0_ddr3_dm[1]}]

# PadFunction: IO_L3P_T0_DQS_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dqs_p[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c0_ddr3_dqs_p[0]}]

# PadFunction: IO_L3N_T0_DQS_32
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c0_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN AE18 [get_ports {c0_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN AF18 [get_ports {c0_ddr3_dqs_n[0]}]

# PadFunction: IO_L15P_T2_DQS_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_dqs_p[1]}]
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c0_ddr3_dqs_p[1]}]

# PadFunction: IO_L15N_T2_DQS_32
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c0_ddr3_dqs_n[1]}]
set_property PACKAGE_PIN AD20 [get_ports {c0_ddr3_dqs_p[1]}]
set_property PACKAGE_PIN AE20 [get_ports {c0_ddr3_dqs_n[1]}]

# PadFunction: IO_L20P_T3_32
set_property VCCAUX_IO NORMAL [get_ports {c0_ddr3_ck_p[0]}]
set_property SLEW FAST [get_ports {c0_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_ck_p[0]}]

# PadFunction: IO_L20N_T3_32
set_property SLEW FAST [get_ports {c0_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_ck_n[0]}]
set_property PACKAGE_PIN V16 [get_ports {c0_ddr3_ck_p[0]}]
set_property PACKAGE_PIN V17 [get_ports {c0_ddr3_ck_n[0]}]




current_instance ctrl_ddr3_inst
set_property LOC PHASER_OUT_PHY_X1Y2 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y3 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y1 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]


## set_property LOC PHASER_IN_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y3 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y1 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X1Y2 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property LOC OUT_FIFO_X1Y3 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X1Y1 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]


set_property LOC IN_FIFO_X1Y3 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y1 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X1Y43 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y19 [get_cells -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X1Y0 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]



set_multicycle_path -setup -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 6

set_multicycle_path -hold -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -setup -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 2
set_multicycle_path -hold -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 1

#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_max_delay -to [get_pins -hier -include_replicated_objects -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1_reg[*]/D}] 20.000
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000
#set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]
set_false_path -through [get_nets -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst_i}]

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20.000

##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-107
## Data Width: 16
## Time Period: 2000
## Data Mask: 1
##################################################################################################

current_instance -quiet
set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_p[0]}]

#create_clock -period 5 [get_ports c1_sys_clk_i]

############## NET - IOSTANDARD ##################


# PadFunction: IO_L24N_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[0]}]
set_property PACKAGE_PIN AF2 [get_ports {c1_ddr3_dq[0]}]

# PadFunction: IO_L23P_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[1]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[1]}]
set_property PACKAGE_PIN AE6 [get_ports {c1_ddr3_dq[1]}]

# PadFunction: IO_L23N_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[2]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[2]}]
set_property PACKAGE_PIN AE5 [get_ports {c1_ddr3_dq[2]}]

# PadFunction: IO_L22P_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[3]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[3]}]
set_property PACKAGE_PIN AE3 [get_ports {c1_ddr3_dq[3]}]

# PadFunction: IO_L22N_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[4]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[4]}]
set_property PACKAGE_PIN AE2 [get_ports {c1_ddr3_dq[4]}]

# PadFunction: IO_L20P_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[5]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[5]}]
set_property PACKAGE_PIN AD1 [get_ports {c1_ddr3_dq[5]}]

# PadFunction: IO_L20N_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[6]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[6]}]
set_property PACKAGE_PIN AE1 [get_ports {c1_ddr3_dq[6]}]

# PadFunction: IO_L19P_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[7]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[7]}]
set_property PACKAGE_PIN AD4 [get_ports {c1_ddr3_dq[7]}]

# PadFunction: IO_L17P_T2_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[8]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[8]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[8]}]
set_property PACKAGE_PIN Y6 [get_ports {c1_ddr3_dq[8]}]

# PadFunction: IO_L17N_T2_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[9]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[9]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[9]}]
set_property PACKAGE_PIN Y5 [get_ports {c1_ddr3_dq[9]}]

# PadFunction: IO_L16P_T2_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[10]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[10]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[10]}]
set_property PACKAGE_PIN AB6 [get_ports {c1_ddr3_dq[10]}]

# PadFunction: IO_L16N_T2_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[11]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[11]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[11]}]
set_property PACKAGE_PIN AC6 [get_ports {c1_ddr3_dq[11]}]

# PadFunction: IO_L14P_T2_SRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[12]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[12]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[12]}]
set_property PACKAGE_PIN AC4 [get_ports {c1_ddr3_dq[12]}]

# PadFunction: IO_L14N_T2_SRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[13]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[13]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[13]}]
set_property PACKAGE_PIN AC3 [get_ports {c1_ddr3_dq[13]}]

# PadFunction: IO_L13P_T2_MRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[14]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[14]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[14]}]
set_property PACKAGE_PIN AA4 [get_ports {c1_ddr3_dq[14]}]

# PadFunction: IO_L13N_T2_MRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dq[15]}]
set_property SLEW FAST [get_ports {c1_ddr3_dq[15]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {c1_ddr3_dq[15]}]
set_property PACKAGE_PIN AB4 [get_ports {c1_ddr3_dq[15]}]

# PadFunction: IO_L2N_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[12]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[12]}]
set_property PACKAGE_PIN U1 [get_ports {c1_ddr3_addr[12]}]

# PadFunction: IO_L2P_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[11]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[11]}]
set_property PACKAGE_PIN U2 [get_ports {c1_ddr3_addr[11]}]

# PadFunction: IO_L3N_T0_DQS_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[10]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[10]}]
set_property PACKAGE_PIN W5 [get_ports {c1_ddr3_addr[10]}]

# PadFunction: IO_L3P_T0_DQS_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[9]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[9]}]
set_property PACKAGE_PIN W6 [get_ports {c1_ddr3_addr[9]}]

# PadFunction: IO_L10N_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[8]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[8]}]
set_property PACKAGE_PIN Y1 [get_ports {c1_ddr3_addr[8]}]

# PadFunction: IO_L4P_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[7]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[7]}]
set_property PACKAGE_PIN V3 [get_ports {c1_ddr3_addr[7]}]

# PadFunction: IO_L10P_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[6]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[6]}]
set_property PACKAGE_PIN W1 [get_ports {c1_ddr3_addr[6]}]

# PadFunction: IO_L5P_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[5]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[5]}]
set_property PACKAGE_PIN U7 [get_ports {c1_ddr3_addr[5]}]

# PadFunction: IO_L8P_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[4]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[4]}]
set_property PACKAGE_PIN V2 [get_ports {c1_ddr3_addr[4]}]

# PadFunction: IO_L7N_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[3]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[3]}]
set_property PACKAGE_PIN Y2 [get_ports {c1_ddr3_addr[3]}]

# PadFunction: IO_L7P_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[2]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[2]}]
set_property PACKAGE_PIN Y3 [get_ports {c1_ddr3_addr[2]}]

# PadFunction: IO_L8N_T1_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[1]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[1]}]
set_property PACKAGE_PIN V1 [get_ports {c1_ddr3_addr[1]}]

# PadFunction: IO_L6P_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_addr[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[0]}]
set_property PACKAGE_PIN V4 [get_ports {c1_ddr3_addr[0]}]

# PadFunction: IO_L5N_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_ba[2]}]
set_property SLEW FAST [get_ports {c1_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[2]}]
set_property PACKAGE_PIN V6 [get_ports {c1_ddr3_ba[2]}]

# PadFunction: IO_L11N_T1_SRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_ba[1]}]
set_property SLEW FAST [get_ports {c1_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[1]}]
set_property PACKAGE_PIN AC2 [get_ports {c1_ddr3_ba[1]}]

# PadFunction: IO_L11P_T1_SRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_ba[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[0]}]
set_property PACKAGE_PIN AB2 [get_ports {c1_ddr3_ba[0]}]

# PadFunction: IO_L9N_T1_DQS_34
set_property VCCAUX_IO NORMAL [get_ports c1_ddr3_ras_n]
set_property SLEW FAST [get_ports c1_ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports c1_ddr3_ras_n]
set_property PACKAGE_PIN AC1 [get_ports c1_ddr3_ras_n]

# PadFunction: IO_L9P_T1_DQS_34
set_property VCCAUX_IO NORMAL [get_ports c1_ddr3_cas_n]
set_property SLEW FAST [get_ports c1_ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports c1_ddr3_cas_n]
set_property PACKAGE_PIN AB1 [get_ports c1_ddr3_cas_n]

# PadFunction: IO_L4N_T0_34
set_property VCCAUX_IO NORMAL [get_ports c1_ddr3_we_n]
set_property SLEW FAST [get_ports c1_ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports c1_ddr3_we_n]
set_property PACKAGE_PIN W3 [get_ports c1_ddr3_we_n]

# PadFunction: IO_L18N_T2_34
set_property VCCAUX_IO NORMAL [get_ports c1_ddr3_reset_n]
set_property SLEW FAST [get_ports c1_ddr3_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports c1_ddr3_reset_n]
set_property PACKAGE_PIN AD5 [get_ports c1_ddr3_reset_n]

# PadFunction: IO_0_VRN_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_cke[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_cke[0]}]
set_property PACKAGE_PIN U4 [get_ports {c1_ddr3_cke[0]}]

# PadFunction: IO_L12P_T1_MRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_odt[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_odt[0]}]
set_property PACKAGE_PIN AA3 [get_ports {c1_ddr3_odt[0]}]

# PadFunction: IO_L12N_T1_MRCC_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_cs_n[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_cs_n[0]}]
set_property PACKAGE_PIN AA2 [get_ports {c1_ddr3_cs_n[0]}]

# PadFunction: IO_L24P_T3_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dm[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dm[0]}]
set_property PACKAGE_PIN AF3 [get_ports {c1_ddr3_dm[0]}]

# PadFunction: IO_L18P_T2_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dm[1]}]
set_property SLEW FAST [get_ports {c1_ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dm[1]}]
set_property PACKAGE_PIN AD6 [get_ports {c1_ddr3_dm[1]}]

# PadFunction: IO_L21P_T3_DQS_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dqs_p[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c1_ddr3_dqs_p[0]}]

# PadFunction: IO_L21N_T3_DQS_34
set_property SLEW FAST [get_ports {c1_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c1_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN AF5 [get_ports {c1_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN AF4 [get_ports {c1_ddr3_dqs_n[0]}]

# PadFunction: IO_L15P_T2_DQS_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_dqs_p[1]}]
set_property SLEW FAST [get_ports {c1_ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c1_ddr3_dqs_p[1]}]

# PadFunction: IO_L15N_T2_DQS_34
set_property SLEW FAST [get_ports {c1_ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {c1_ddr3_dqs_n[1]}]
set_property PACKAGE_PIN AA5 [get_ports {c1_ddr3_dqs_p[1]}]
set_property PACKAGE_PIN AB5 [get_ports {c1_ddr3_dqs_n[1]}]

# PadFunction: IO_L1P_T0_34
set_property VCCAUX_IO NORMAL [get_ports {c1_ddr3_ck_p[0]}]
set_property SLEW FAST [get_ports {c1_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_ck_p[0]}]

# PadFunction: IO_L1N_T0_34
set_property SLEW FAST [get_ports {c1_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_ck_n[0]}]
set_property PACKAGE_PIN U6 [get_ports {c1_ddr3_ck_p[0]}]
set_property PACKAGE_PIN U5 [get_ports {c1_ddr3_ck_n[0]}]




current_instance ctrl_ddr3_inst
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y8 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


## set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y9 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y8 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X1Y11 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X1Y10 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X1Y9 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X1Y8 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X1Y9 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y8 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X1Y119 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y107 [get_cells -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]




##################################################################################################
## Controller 2
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-107
## Data Width: 16
## Time Period: 2000
## Data Mask: 1
##################################################################################################

current_instance -quiet
set_property IO_BUFFER_TYPE NONE [get_ports {c2_ddr3_ck_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {c2_ddr3_ck_p[0]}]

#create_clock -period 5 [get_ports c2_sys_clk_i]

############## NET - IOSTANDARD ##################


# PadFunction: IO_L17P_T2_A26_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[0]}]
set_property PACKAGE_PIN F19 [get_ports {c2_ddr3_dq[0]}]

# PadFunction: IO_L17N_T2_A25_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[1]}]
set_property PACKAGE_PIN E20 [get_ports {c2_ddr3_dq[1]}]

# PadFunction: IO_L16P_T2_A28_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[2]}]
set_property PACKAGE_PIN G19 [get_ports {c2_ddr3_dq[2]}]

# PadFunction: IO_L16N_T2_A27_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[3]}]
set_property PACKAGE_PIN F20 [get_ports {c2_ddr3_dq[3]}]

# PadFunction: IO_L14P_T2_SRCC_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[4]}]
set_property PACKAGE_PIN H17 [get_ports {c2_ddr3_dq[4]}]

# PadFunction: IO_L14N_T2_SRCC_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[5]}]
set_property PACKAGE_PIN H18 [get_ports {c2_ddr3_dq[5]}]

# PadFunction: IO_L13P_T2_MRCC_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[6]}]
set_property PACKAGE_PIN E18 [get_ports {c2_ddr3_dq[6]}]

# PadFunction: IO_L18N_T2_A23_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[7]}]
set_property PACKAGE_PIN G20 [get_ports {c2_ddr3_dq[7]}]

# PadFunction: IO_L24N_T3_RS0_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[8]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[8]}]
set_property PACKAGE_PIN K18 [get_ports {c2_ddr3_dq[8]}]

# PadFunction: IO_L23P_T3_FOE_B_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[9]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[9]}]
set_property PACKAGE_PIN M17 [get_ports {c2_ddr3_dq[9]}]

# PadFunction: IO_L23N_T3_FWE_B_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[10]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[10]}]
set_property PACKAGE_PIN L18 [get_ports {c2_ddr3_dq[10]}]

# PadFunction: IO_L22P_T3_A17_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[11]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[11]}]
set_property PACKAGE_PIN K16 [get_ports {c2_ddr3_dq[11]}]

# PadFunction: IO_L22N_T3_A16_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[12]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[12]}]
set_property PACKAGE_PIN K17 [get_ports {c2_ddr3_dq[12]}]

# PadFunction: IO_L20P_T3_A20_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[13]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[13]}]
set_property PACKAGE_PIN J18 [get_ports {c2_ddr3_dq[13]}]

# PadFunction: IO_L20N_T3_A19_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[14]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[14]}]
set_property PACKAGE_PIN J19 [get_ports {c2_ddr3_dq[14]}]

# PadFunction: IO_L19P_T3_A22_15
set_property SLEW FAST [get_ports {c2_ddr3_dq[15]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dq[15]}]
set_property PACKAGE_PIN K20 [get_ports {c2_ddr3_dq[15]}]

# PadFunction: IO_L2N_T0_AD8N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[12]}]
set_property PACKAGE_PIN A19 [get_ports {c2_ddr3_addr[12]}]

# PadFunction: IO_L2P_T0_AD8P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[11]}]
set_property PACKAGE_PIN A18 [get_ports {c2_ddr3_addr[11]}]

# PadFunction: IO_L3N_T0_DQS_AD1N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[10]}]
set_property PACKAGE_PIN A17 [get_ports {c2_ddr3_addr[10]}]

# PadFunction: IO_L3P_T0_DQS_AD1P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[9]}]
set_property PACKAGE_PIN B17 [get_ports {c2_ddr3_addr[9]}]

# PadFunction: IO_L9P_T1_DQS_AD11P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[8]}]
set_property PACKAGE_PIN J15 [get_ports {c2_ddr3_addr[8]}]

# PadFunction: IO_L6P_T0_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[7]}]
set_property PACKAGE_PIN D15 [get_ports {c2_ddr3_addr[7]}]

# PadFunction: IO_L5P_T0_AD2P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[6]}]
set_property PACKAGE_PIN C17 [get_ports {c2_ddr3_addr[6]}]

# PadFunction: IO_L5N_T0_AD2N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[5]}]
set_property PACKAGE_PIN C18 [get_ports {c2_ddr3_addr[5]}]

# PadFunction: IO_L7N_T1_AD10N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[4]}]
set_property PACKAGE_PIN G16 [get_ports {c2_ddr3_addr[4]}]

# PadFunction: IO_L4N_T0_AD9N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[3]}]
set_property PACKAGE_PIN B19 [get_ports {c2_ddr3_addr[3]}]

# PadFunction: IO_L7P_T1_AD10P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[2]}]
set_property PACKAGE_PIN H16 [get_ports {c2_ddr3_addr[2]}]

# PadFunction: IO_L8N_T1_AD3N_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[1]}]
set_property PACKAGE_PIN F15 [get_ports {c2_ddr3_addr[1]}]

# PadFunction: IO_L8P_T1_AD3P_15
set_property SLEW FAST [get_ports {c2_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_addr[0]}]
set_property PACKAGE_PIN G15 [get_ports {c2_ddr3_addr[0]}]

# PadFunction: IO_L10P_T1_AD4P_15
set_property SLEW FAST [get_ports {c2_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_ba[2]}]
set_property PACKAGE_PIN E15 [get_ports {c2_ddr3_ba[2]}]

# PadFunction: IO_L12P_T1_MRCC_AD5P_15
set_property SLEW FAST [get_ports {c2_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_ba[1]}]
set_property PACKAGE_PIN F17 [get_ports {c2_ddr3_ba[1]}]

# PadFunction: IO_L10N_T1_AD4N_15
set_property SLEW FAST [get_ports {c2_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_ba[0]}]
set_property PACKAGE_PIN E16 [get_ports {c2_ddr3_ba[0]}]

# PadFunction: IO_L9N_T1_DQS_AD11N_15
set_property SLEW FAST [get_ports c2_ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports c2_ddr3_ras_n]
set_property PACKAGE_PIN J16 [get_ports c2_ddr3_ras_n]

# PadFunction: IO_L4P_T0_AD9P_15
set_property SLEW FAST [get_ports c2_ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports c2_ddr3_cas_n]
set_property PACKAGE_PIN C19 [get_ports c2_ddr3_cas_n]

# PadFunction: IO_L11P_T1_SRCC_AD12P_15
set_property SLEW FAST [get_ports c2_ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports c2_ddr3_we_n]
set_property PACKAGE_PIN G17 [get_ports c2_ddr3_we_n]

# PadFunction: IO_L13N_T2_MRCC_15
set_property SLEW FAST [get_ports c2_ddr3_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports c2_ddr3_reset_n]
set_property PACKAGE_PIN D18 [get_ports c2_ddr3_reset_n]

# PadFunction: IO_0_15
set_property SLEW FAST [get_ports {c2_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_cke[0]}]
set_property PACKAGE_PIN K15 [get_ports {c2_ddr3_cke[0]}]

# PadFunction: IO_L11N_T1_SRCC_AD12N_15
set_property SLEW FAST [get_ports {c2_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_odt[0]}]
set_property PACKAGE_PIN F18 [get_ports {c2_ddr3_odt[0]}]

# PadFunction: IO_L12N_T1_MRCC_AD5N_15
set_property SLEW FAST [get_ports {c2_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_cs_n[0]}]
set_property PACKAGE_PIN E17 [get_ports {c2_ddr3_cs_n[0]}]

# PadFunction: IO_L18P_T2_A24_15
set_property SLEW FAST [get_ports {c2_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dm[0]}]
set_property PACKAGE_PIN H19 [get_ports {c2_ddr3_dm[0]}]

# PadFunction: IO_L24P_T3_RS1_15
set_property SLEW FAST [get_ports {c2_ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c2_ddr3_dm[1]}]
set_property PACKAGE_PIN L17 [get_ports {c2_ddr3_dm[1]}]

# PadFunction: IO_L15P_T2_DQS_15
set_property SLEW FAST [get_ports {c2_ddr3_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_dqs_p[0]}]

# PadFunction: IO_L15N_T2_DQS_ADV_B_15
set_property SLEW FAST [get_ports {c2_ddr3_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN D19 [get_ports {c2_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN D20 [get_ports {c2_ddr3_dqs_n[0]}]

# PadFunction: IO_L21P_T3_DQS_15
set_property SLEW FAST [get_ports {c2_ddr3_dqs_p[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_dqs_p[1]}]

# PadFunction: IO_L21N_T3_DQS_A18_15
set_property SLEW FAST [get_ports {c2_ddr3_dqs_n[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c2_ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_dqs_n[1]}]
set_property PACKAGE_PIN L19 [get_ports {c2_ddr3_dqs_p[1]}]
set_property PACKAGE_PIN L20 [get_ports {c2_ddr3_dqs_n[1]}]

# PadFunction: IO_L1P_T0_AD0P_15
set_property SLEW FAST [get_ports {c2_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_ck_p[0]}]

# PadFunction: IO_L1N_T0_AD0N_15
set_property SLEW FAST [get_ports {c2_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c2_ddr3_ck_n[0]}]
set_property PACKAGE_PIN C16 [get_ports {c2_ddr3_ck_p[0]}]
set_property PACKAGE_PIN B16 [get_ports {c2_ddr3_ck_n[0]}]




current_instance ctrl_ddr3_inst
set_property LOC PHASER_OUT_PHY_X0Y15 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y14 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y13 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y12 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


## set_property LOC PHASER_IN_PHY_X0Y15 [get_cells  -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y14 [get_cells  -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y13 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y12 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X0Y15 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y14 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y13 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y12 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X0Y13 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y12 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X0Y3 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X0Y3 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X0Y169 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y157 [get_cells -hier -filter {NAME =~ */c2_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X0Y3 [get_cells -hier -filter {NAME =~ */c2_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X0Y3 [get_cells -hier -filter {NAME =~ */c2_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]




##################################################################################################
## Controller 3
## Memory Device: DDR3_SDRAM->Components->MT41K64M16XX-107
## Data Width: 16
## Time Period: 2000
## Data Mask: 1
##################################################################################################

current_instance -quiet
set_property IO_BUFFER_TYPE NONE [get_ports {c3_ddr3_ck_n[0]}]
set_property IO_BUFFER_TYPE NONE [get_ports {c3_ddr3_ck_p[0]}]

#create_clock -period 5 [get_ports c3_sys_clk_i]

############## NET - IOSTANDARD ##################


# PadFunction: IO_L24N_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[0]}]
set_property PACKAGE_PIN A12 [get_ports {c3_ddr3_dq[0]}]

# PadFunction: IO_L23P_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[1]}]
set_property PACKAGE_PIN B15 [get_ports {c3_ddr3_dq[1]}]

# PadFunction: IO_L23N_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[2]}]
set_property PACKAGE_PIN A15 [get_ports {c3_ddr3_dq[2]}]

# PadFunction: IO_L22P_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[3]}]
set_property PACKAGE_PIN B10 [get_ports {c3_ddr3_dq[3]}]

# PadFunction: IO_L22N_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[4]}]
set_property PACKAGE_PIN A10 [get_ports {c3_ddr3_dq[4]}]

# PadFunction: IO_L20P_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[5]}]
set_property PACKAGE_PIN B12 [get_ports {c3_ddr3_dq[5]}]

# PadFunction: IO_L20N_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[6]}]
set_property PACKAGE_PIN B11 [get_ports {c3_ddr3_dq[6]}]

# PadFunction: IO_L19P_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[7]}]
set_property PACKAGE_PIN C14 [get_ports {c3_ddr3_dq[7]}]

# PadFunction: IO_L17P_T2_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[8]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[8]}]
set_property PACKAGE_PIN D14 [get_ports {c3_ddr3_dq[8]}]

# PadFunction: IO_L17N_T2_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[9]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[9]}]
set_property PACKAGE_PIN D13 [get_ports {c3_ddr3_dq[9]}]

# PadFunction: IO_L16P_T2_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[10]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[10]}]
set_property PACKAGE_PIN G12 [get_ports {c3_ddr3_dq[10]}]

# PadFunction: IO_L16N_T2_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[11]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[11]}]
set_property PACKAGE_PIN F12 [get_ports {c3_ddr3_dq[11]}]

# PadFunction: IO_L14P_T2_SRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[12]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[12]}]
set_property PACKAGE_PIN E11 [get_ports {c3_ddr3_dq[12]}]

# PadFunction: IO_L14N_T2_SRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[13]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[13]}]
set_property PACKAGE_PIN D11 [get_ports {c3_ddr3_dq[13]}]

# PadFunction: IO_L13P_T2_MRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[14]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[14]}]
set_property PACKAGE_PIN C12 [get_ports {c3_ddr3_dq[14]}]

# PadFunction: IO_L13N_T2_MRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_dq[15]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dq[15]}]
set_property PACKAGE_PIN C11 [get_ports {c3_ddr3_dq[15]}]

# PadFunction: IO_L2N_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[12]}]
set_property PACKAGE_PIN G9 [get_ports {c3_ddr3_addr[12]}]

# PadFunction: IO_L6P_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[11]}]
set_property PACKAGE_PIN H12 [get_ports {c3_ddr3_addr[11]}]

# PadFunction: IO_L3N_T0_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[10]}]
set_property PACKAGE_PIN H13 [get_ports {c3_ddr3_addr[10]}]

# PadFunction: IO_L3P_T0_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[9]}]
set_property PACKAGE_PIN J13 [get_ports {c3_ddr3_addr[9]}]

# PadFunction: IO_L4N_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[8]}]
set_property PACKAGE_PIN J10 [get_ports {c3_ddr3_addr[8]}]

# PadFunction: IO_L8N_T1_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[7]}]
set_property PACKAGE_PIN D8 [get_ports {c3_ddr3_addr[7]}]

# PadFunction: IO_L5P_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[6]}]
set_property PACKAGE_PIN H14 [get_ports {c3_ddr3_addr[6]}]

# PadFunction: IO_L8P_T1_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[5]}]
set_property PACKAGE_PIN D9 [get_ports {c3_ddr3_addr[5]}]

# PadFunction: IO_L2P_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[4]}]
set_property PACKAGE_PIN G10 [get_ports {c3_ddr3_addr[4]}]

# PadFunction: IO_L7P_T1_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[3]}]
set_property PACKAGE_PIN F9 [get_ports {c3_ddr3_addr[3]}]

# PadFunction: IO_L7N_T1_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[2]}]
set_property PACKAGE_PIN F8 [get_ports {c3_ddr3_addr[2]}]

# PadFunction: IO_L4P_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[1]}]
set_property PACKAGE_PIN J11 [get_ports {c3_ddr3_addr[1]}]

# PadFunction: IO_L5N_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_addr[0]}]
set_property PACKAGE_PIN G14 [get_ports {c3_ddr3_addr[0]}]

# PadFunction: IO_L10P_T1_16
set_property SLEW FAST [get_ports {c3_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_ba[2]}]
set_property PACKAGE_PIN C9 [get_ports {c3_ddr3_ba[2]}]

# PadFunction: IO_L11P_T1_SRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_ba[1]}]
set_property PACKAGE_PIN G11 [get_ports {c3_ddr3_ba[1]}]

# PadFunction: IO_L11N_T1_SRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_ba[0]}]
set_property PACKAGE_PIN F10 [get_ports {c3_ddr3_ba[0]}]

# PadFunction: IO_L9N_T1_DQS_16
set_property SLEW FAST [get_ports c3_ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports c3_ddr3_ras_n]
set_property PACKAGE_PIN A8 [get_ports c3_ddr3_ras_n]

# PadFunction: IO_L9P_T1_DQS_16
set_property SLEW FAST [get_ports c3_ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports c3_ddr3_cas_n]
set_property PACKAGE_PIN A9 [get_ports c3_ddr3_cas_n]

# PadFunction: IO_L10N_T1_16
set_property SLEW FAST [get_ports c3_ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports c3_ddr3_we_n]
set_property PACKAGE_PIN B9 [get_ports c3_ddr3_we_n]

# PadFunction: IO_L18N_T2_16
set_property SLEW FAST [get_ports c3_ddr3_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports c3_ddr3_reset_n]
set_property PACKAGE_PIN E12 [get_ports c3_ddr3_reset_n]

# PadFunction: IO_0_16
set_property SLEW FAST [get_ports {c3_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_cke[0]}]
set_property PACKAGE_PIN J8 [get_ports {c3_ddr3_cke[0]}]

# PadFunction: IO_L12P_T1_MRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_odt[0]}]
set_property PACKAGE_PIN E10 [get_ports {c3_ddr3_odt[0]}]

# PadFunction: IO_L12N_T1_MRCC_16
set_property SLEW FAST [get_ports {c3_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_cs_n[0]}]
set_property PACKAGE_PIN D10 [get_ports {c3_ddr3_cs_n[0]}]

# PadFunction: IO_L24P_T3_16
set_property SLEW FAST [get_ports {c3_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dm[0]}]
set_property PACKAGE_PIN A13 [get_ports {c3_ddr3_dm[0]}]

# PadFunction: IO_L18P_T2_16
set_property SLEW FAST [get_ports {c3_ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c3_ddr3_dm[1]}]
set_property PACKAGE_PIN E13 [get_ports {c3_ddr3_dm[1]}]

# PadFunction: IO_L21P_T3_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_dqs_p[0]}]

# PadFunction: IO_L21N_T3_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN B14 [get_ports {c3_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN A14 [get_ports {c3_ddr3_dqs_n[0]}]

# PadFunction: IO_L15P_T2_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_dqs_p[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_dqs_p[1]}]

# PadFunction: IO_L15N_T2_DQS_16
set_property SLEW FAST [get_ports {c3_ddr3_dqs_n[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c3_ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_dqs_n[1]}]
set_property PACKAGE_PIN F14 [get_ports {c3_ddr3_dqs_p[1]}]
set_property PACKAGE_PIN F13 [get_ports {c3_ddr3_dqs_n[1]}]

# PadFunction: IO_L1P_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_ck_p[0]}]

# PadFunction: IO_L1N_T0_16
set_property SLEW FAST [get_ports {c3_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c3_ddr3_ck_n[0]}]
set_property PACKAGE_PIN H9 [get_ports {c3_ddr3_ck_p[0]}]
set_property PACKAGE_PIN H8 [get_ports {c3_ddr3_ck_n[0]}]




current_instance ctrl_ddr3_inst
set_property LOC PHASER_OUT_PHY_X0Y19 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y18 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y17 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y16 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


## set_property LOC PHASER_IN_PHY_X0Y19 [get_cells  -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y18 [get_cells  -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y17 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y16 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X0Y19 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y18 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y17 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y16 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X0Y17 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y16 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X0Y4 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X0Y4 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X0Y219 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y207 [get_cells -hier -filter {NAME =~ */c3_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X0Y4 [get_cells -hier -filter {NAME =~ */c3_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X0Y4 [get_cells -hier -filter {NAME =~ */c3_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]





####################################################################################
# Constraints from file : 'usw2000_timing.xdc'
####################################################################################

## TIMING CONSTRAINTS

## Exceptions priority
# 1- Clock Groups (set_clock_groups)
# 2- False Path (set_false_path)
# 3- Maximum and Minimum Delay Path (set_max_delay and set_min_delay)
# 4- Multicycle Paths (set_multicycle_path)

######################################################################
## CREATE_CLOCK
######################################################################

current_instance -quiet
create_clock -period 37.037 -name clk_27mhz -waveform {0.000 18.519} [get_ports clk_27mhz_i]
create_clock -period 74.074 -name clk_13mhz5 -waveform {0.000 37.037} [get_ports clk_13mhz5_i]
create_clock -period 37.037 -name clk_27mhz -waveform {0.000 18.519} [get_ports clk_27mhz_i]
create_clock -period 3.367 -name tx0_outclk -waveform {0.000 1.684} [get_pins -hier -filter {name=~*uhdsdi_gen[0].*GTXE2*/TXOUTCLK}]
create_clock -period 3.367 -name rx0_outclk -waveform {0.000 1.684} [get_pins -hier -filter {name=~*uhdsdi_gen[0].*GTXE2*/RXOUTCLK}]
create_clock -period 3.367 -name rx1_outclk -waveform {0.000 1.684} [get_pins -hier -filter {name=~*uhdsdi_gen[1].*GTXE2*/RXOUTCLK}]
create_clock -period 3.367 -name rx2_outclk -waveform {0.000 1.684} [get_pins -hier -filter {name=~*uhdsdi_gen[2].*GTXE2*/RXOUTCLK}]
create_clock -period 3.367 -name rx3_outclk -waveform {0.000 1.684} [get_pins -hier -filter {name=~*uhdsdi_gen[3].*GTXE2*/RXOUTCLK}]
#create_clock -period 20.000 -name rmii_clk -waveform {0.000 10.000} [get_ports rmii_clk_i]
#create_clock -period 20.000 -name rmii_mdc -waveform {0.000 10.000} [get_ports rmii_mdc_i]
create_clock -period 8.000 -name rmii_clk -waveform {0.000 4.000} [get_ports rgmii_txc_i]
create_clock -period 20.000 -name rmii_mdc -waveform {0.000 10.000} [get_ports phy_emulator_mdc]
create_clock -period 6.734 -name mgtclk0 -waveform {0.000 3.367} [get_ports {gtx_refclk_p_i[0]}]
create_clock -period 6.734 -name mgtclk1 -waveform {0.000 3.367} [get_ports {gtx_refclk_p_i[1]}]
create_clock -period 20.300 -name aud_clk -waveform {0.000 10.150} [get_ports f_si_a_clk3_p]

######################################################################
## CREATE_GENERATED_CLOCK
######################################################################

create_generated_clock -name clk_50mhz clk_gen_inst/pll_20mhz_inst/CLKOUT0
create_generated_clock -name clk_125mhz clk_gen_inst/pll_20mhz_inst/CLKOUT1
create_generated_clock -name clk_135mhz clk_gen_inst/pll_27mhz_inst/CLKOUT1



create_generated_clock -name nidru_clk0 -source [get_pins -hier -filter {name=~*uhdsdi_gen[0].*GTXE2*/RXOUTCLK}] -divide_by 2 [get_pins -hier -filter {name=~*uhdsdi_gen[0].**NIDRU_INST/CLK}]
create_generated_clock -name nidru_clk1 -source [get_pins -hier -filter {name=~*uhdsdi_gen[1].*GTXE2*/RXOUTCLK}] -divide_by 2 [get_pins -hier -filter {name=~*uhdsdi_gen[1].**NIDRU_INST/CLK}]
create_generated_clock -name nidru_clk2 -source [get_pins -hier -filter {name=~*uhdsdi_gen[2].*GTXE2*/RXOUTCLK}] -divide_by 2 [get_pins -hier -filter {name=~*uhdsdi_gen[2].**NIDRU_INST/CLK}]
create_generated_clock -name nidru_clk3 -source [get_pins -hier -filter {name=~*uhdsdi_gen[3].*GTXE2*/RXOUTCLK}] -divide_by 2 [get_pins -hier -filter {name=~*uhdsdi_gen[3].**NIDRU_INST/CLK}]
create_generated_clock -name drpclk_i -source [get_ports {gtx_refclk_p_i[1]}] -divide_by 2 [get_pins -hier -filter name=~*MGTCLKIN1*/ODIV2]


######################################################################
## SET_INPUT_DELAY
######################################################################
set_input_delay -clock rmii_clk -max 4.100 [get_ports {{rgmii_txd_i[*]} rgmii_tx_ctl_i}]
set_input_delay -clock rmii_clk -min 4.000 [get_ports {{rgmii_txd_i[*]} rgmii_tx_ctl_i}]

######################################################################
## SET_OUTPUT_DELAY
######################################################################

######################################################################
## SET_CLOCK_GROUPS
######################################################################
## EXCLUSIVE
set_clock_groups -physically_exclusive -group [get_clocks -include_generated_clocks rx0_outclk] -group [get_clocks -include_generated_clocks rx1_outclk] -group [get_clocks -include_generated_clocks rx2_outclk] -group [get_clocks -include_generated_clocks rx3_outclk]


## ASYNCHROUNOUS
set_clock_groups -asynchronous -group [get_clocks rx1_outclk] -group [get_clocks drpclk_i]
set_clock_groups -asynchronous -group [get_clocks rx2_outclk] -group [get_clocks drpclk_i]
set_clock_groups -asynchronous -group [get_clocks rx3_outclk] -group [get_clocks drpclk_i]
set_clock_groups -asynchronous -group [get_clocks drpclk_i] -group [get_clocks rx0_outclk*]
set_clock_groups -asynchronous -group [get_clocks drpclk_i] -group [get_clocks rx1_outclk]
set_clock_groups -asynchronous -group [get_clocks drpclk_i] -group [get_clocks rx2_outclk]
set_clock_groups -asynchronous -group [get_clocks drpclk_i] -group [get_clocks rx3_outclk]


######################################################################
## SET_FALSE_PATH
######################################################################

set_false_path -from [get_clocks aud_clk] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks aud_clk] -to [get_clocks clkout2]

set_false_path -from [get_clocks clk_125mhz] -to [get_clocks clkout2]
set_false_path -from [get_clocks clk_125mhz] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks clk_125mhz] -to [get_clocks rmii_clk]
set_false_path -from [get_clocks clk_125mhz] -to [get_clocks rmii_mdc]
set_false_path -from [get_clocks clk_125mhz] -to [get_clocks clk_125_90mhz]

set_false_path -from [get_clocks clk_13mhz5] -to [get_clocks clk_135mhz]
set_false_path -from [get_clocks clk_13mhz5] -to [get_clocks clk_50mhz]

set_false_path -from [get_clocks clk_135mhz] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks clk_135mhz] -to [get_clocks clk_13mhz5]
set_false_path -from [get_clocks clk_135mhz] -to [get_clocks clkout2]

set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clk_125mhz]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clk_13mhz5]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clk_135mhz]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clk_pll_*]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clkout1]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks clkout2]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks rx?_outclk]
set_false_path -from [get_clocks clk_50mhz] -to [get_clocks drpclk_i]

set_false_path -from [get_clocks clkout2] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks clkout2] -to [get_clocks clk_pll_*]
set_false_path -from [get_clocks clkout2] -to [get_clocks clk_125mhz]
set_false_path -from [get_clocks clkout2] -to [get_clocks clk_135mhz]

set_false_path -from [get_clocks drpclk_i] -to [get_clocks clkout*]

set_false_path -from [get_clocks rmii_clk] -to [get_clocks clk_125mhz]

set_false_path -from [get_clocks rx?_outclk] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks rx?_outclk] -to [get_clocks clk_135mhz]
set_false_path -from [get_clocks rx?_outclk] -to [get_clocks clk_pll_*]
set_false_path -from [get_clocks rx?_outclk] -to [get_clocks clkout2]
set_false_path -from [get_clocks rx?_outclk] -to [get_clocks nidru_clk*]

set_false_path -from [get_clocks clk_pll_*] -to [get_clocks clkout2]
set_false_path -from [get_clocks clk_pll_*] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks clk_pll_i] -to [get_clocks {clk_pll_i_1 clk_pll_i_2 clk_pll_i_3}]
set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_200mhz]

set_false_path -from [get_clocks clkout1] -to [get_clocks drpclk_i]

set_false_path -from [get_clocks mgtclk0] -to [get_clocks clk_50mhz]
set_false_path -from [get_clocks mgtclk0] -to [get_clocks clk_135mhz]

set_false_path -from [get_clocks clk_200mhz] -to [get_clocks clk_pll_*]
set_false_path -from [get_clocks clk_200mhz] -to [get_clocks mmcm_ps_clk_bufg_*]
set_false_path -from [get_clocks clk_200mhz] -to [get_clocks clk_125mhz]

set_false_path -from [get_ports clk_13mhz5_i] -to [get_pins {genlock_top_inst/genlock_inst/rcv_clk_13m5_ins/clk_13m5_d_reg[1]/D}]

set_false_path -to [get_pins -hier *_ss*/D]
set_false_path -to [get_pins -hier *d1_cdc_to*/D]

set_false_path -from [get_pins {vid_fail_det_gen[*].vid_fail_detection_inst/input_fail_det_gen[*].input_fail_det_ins/main_prc.ctrl_reg*/C}]
set_false_path -from [get_pins {vid_fail_det_gen[*].vid_fail_detection_inst/aud_fail_det_in1_ins/aud_silence_det_ins/main_prc.nr_smpls_per_fr_reg[*]/C}]
set_false_path -from [get_pins {vid_fail_det_gen[*].vid_fail_detection_inst/aud_fail_det_in1_ins/aud_overload_det_ins/main_prc.nr_smpls_per_fr_reg[*]/C}]

######################################################################
## SET_MAX_DELAY
######################################################################

# rmii_clk and rmii_mdc to other clocks
#set_max_delay -datapath_only -from [get_clocks rmii_clk] -to [get_clocks clk_125mhz] 8.000
#set_max_delay -datapath_only -from [get_clocks clk_125mhz] -to [get_clocks rmii_clk] 8.000
#set_max_delay -datapath_only -from [get_clocks clk_125mhz] -to [get_clocks rmii_mdc] 8.000


######################################################################
## SET_MULTICYCLE_PATH
######################################################################

set _xlnx_shared_i0 [get_cells * -hier -filter {name =~*TX/TXEDH*      && IS_PRIMITIVE && IS_SEQUENTIAL}]
set_multicycle_path -setup -from $_xlnx_shared_i0 5
set_multicycle_path -hold -from $_xlnx_shared_i0 4


######################################################################
#PARA PODER LLEVAR EL RELOJ DE RX DE RGMII A UN BUFG
######################################################################
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets phy_inst/I_PHY_EMULATOR/RGMII_INTERFACE/rgmii_rxc_ibuf]



####################################################################################
# Constraints from file : 'usw2000.xdc'
####################################################################################

######################################################################
## Transceiver's rx/tx serial input/output
######################################################################
#set_property PACKAGE_PIN R3 [get_ports {rx_gtx_n_i[0]}]
#set_property PACKAGE_PIN R4 [get_ports {rx_gtx_p_i[0]}]
#set_property PACKAGE_PIN P1 [get_ports {tx_gtx_n_o[0]}]
#set_property PACKAGE_PIN P2 [get_ports {tx_gtx_p_o[0]}]
#set_property PACKAGE_PIN N3 [get_ports {rx_gtx_n_i[1]}]
#set_property PACKAGE_PIN N4 [get_ports {rx_gtx_p_i[1]}]
#set_property PACKAGE_PIN M1 [get_ports {tx_gtx_n_o[1]}]
#set_property PACKAGE_PIN M2 [get_ports {tx_gtx_p_o[1]}]
#set_property PACKAGE_PIN G3 [get_ports {rx_gtx_n_i[2]}]
#set_property PACKAGE_PIN G4 [get_ports {rx_gtx_p_i[2]}]
#set_property PACKAGE_PIN F1 [get_ports {tx_gtx_n_o[2]}]
#set_property PACKAGE_PIN F2 [get_ports {tx_gtx_p_o[2]}]
#set_property PACKAGE_PIN E3 [get_ports {rx_gtx_n_i[3]}]
#set_property PACKAGE_PIN E4 [get_ports {rx_gtx_p_i[3]}]
#set_property PACKAGE_PIN D1 [get_ports {tx_gtx_n_o[3]}]
#set_property PACKAGE_PIN D2 [get_ports {tx_gtx_p_o[3]}]
set_property PACKAGE_PIN G3 [get_ports {rx_gtx_n_i[0]}]
set_property PACKAGE_PIN G4 [get_ports {rx_gtx_p_i[0]}]
set_property PACKAGE_PIN F1 [get_ports {tx_gtx_n_o[0]}]
set_property PACKAGE_PIN F2 [get_ports {tx_gtx_p_o[0]}]
set_property PACKAGE_PIN E3 [get_ports {rx_gtx_n_i[1]}]
set_property PACKAGE_PIN E4 [get_ports {rx_gtx_p_i[1]}]
set_property PACKAGE_PIN D1 [get_ports {tx_gtx_n_o[1]}]
set_property PACKAGE_PIN D2 [get_ports {tx_gtx_p_o[1]}]
set_property PACKAGE_PIN R3 [get_ports {rx_gtx_n_i[2]}]
set_property PACKAGE_PIN R4 [get_ports {rx_gtx_p_i[2]}]
set_property PACKAGE_PIN P1 [get_ports {tx_gtx_n_o[2]}]
set_property PACKAGE_PIN P2 [get_ports {tx_gtx_p_o[2]}]
set_property PACKAGE_PIN L3 [get_ports {rx_gtx_n_i[3]}]
set_property PACKAGE_PIN L4 [get_ports {rx_gtx_p_i[3]}]
set_property PACKAGE_PIN K1 [get_ports {tx_gtx_n_o[3]}]
set_property PACKAGE_PIN K2 [get_ports {tx_gtx_p_o[3]}]
######################################################################
## Transceiver's reference clock input
######################################################################
set_property PACKAGE_PIN H6 [get_ports {gtx_refclk_p_i[0]}]
set_property PACKAGE_PIN H5 [get_ports {gtx_refclk_n_i[0]}]
set_property PACKAGE_PIN K6 [get_ports {gtx_refclk_p_i[1]}]
set_property PACKAGE_PIN K5 [get_ports {gtx_refclk_n_i[1]}]
######################################################################
## LMH1297 Pinout  (Dirver/equalizer)
######################################################################
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[0]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports {lock_n_i[0]}]
set_property PULLTYPE PULLUP [get_ports {tx_en_o[0]}]
set_property PULLTYPE PULLUP [get_ports {lock_n_i[0]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[1]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33} [get_ports {lock_n_i[1]}]
set_property PULLTYPE PULLUP [get_ports {tx_en_o[1]}]
set_property PULLTYPE PULLUP [get_ports {lock_n_i[1]}]
##SFP-1 PROVISIONAL
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[2]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports {lock_n_i[2]}]
set_property PULLTYPE PULLUP [get_ports {lock_n_i[2]}]
##SFP-2 PROVISIONAL
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[3]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {lock_n_i[3]}]
set_property PULLTYPE PULLUP [get_ports {lock_n_i[3]}]
######################################################################
## Analog Reference
######################################################################
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33} [get_ports ccvs_hs_i]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports ccvs_oe_i]
set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS33} [get_ports ccvs_vs_i]
######################################################################
## RMII interface
######################################################################
#set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports {rmii_txd_i[0]}]
#set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {rmii_txd_i[1]}]
#set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports rmii_tx_en_i]
#set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {rmii_rxd_o[0]}]
#set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS33} [get_ports {rmii_rxd_o[1]}]
#set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports rmii_rx_en_o]
#set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports rmii_mdio_io]
#set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports rmii_mdc_i]
#set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports rmii_clk_i]
#set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports rmii_rst_n_i]
#set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33} [get_ports rmii_int_n_o]

######################################################################
## MASTER CLOCK
######################################################################
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports clk_27mhz_i]

######################################################################
## RGMII interface
######################################################################
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd_i[3]}]
set_property -dict {PACKAGE_PIN AF22 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd_i[2]}]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd_i[1]}]
set_property -dict {PACKAGE_PIN AE22 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd_i[0]}]
set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS33} [get_ports rgmii_tx_ctl_i]
set_property -dict {PACKAGE_PIN AD25 IOSTANDARD LVCMOS33} [get_ports rgmii_txc_i]
set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd_o[3]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd_o[2]}]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd_o[1]}]
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd_o[0]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports rgmii_rx_ctl_o]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports rgmii_rxc_o]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports phy_emulator_mdio]
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports phy_emulator_mdc]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports phy_emulator_ref_clk]
set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports phy_emulator_resetn]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33} [get_ports phy_emulator_n_int]

######################################################################
## LMH1297 Pinout
######################################################################
#set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[0]}]
#set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[1]}]
#set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[2]}]
#set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33} [get_ports {tx_en_o[3]}]
######################################################################
## REAR LED
######################################################################
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS33} [get_ports {rear_led_o[0]}]
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS33} [get_ports {rear_led_o[1]}]
######################################################################
## SFP Pinout
######################################################################
#set_property PULLTYPE PULLUP [get_ports {tx_en_o[0]}]
#set_property PULLTYPE PULLUP [get_ports {tx_en_o[1]}]
#set_property PULLTYPE PULLUP [get_ports {tx_en_o[2]}]
#set_property PULLTYPE PULLUP [get_ports {tx_en_o[3]}]
######################################################################
## PLL
######################################################################
set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS33} [get_ports vco_center_a_o]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33} [get_ports phc_sd_a_o]
set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports phc_lf_a_o]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports phc_hf_a_o]
##set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33} [get_ports pwm_o]
######################################################################
## BackPlane reference
######################################################################
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS33} [get_ports clk_13mhz5_i]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS33} [get_ports clk_13mhz5_en_o]
######################################################################
## Audio Interface
######################################################################
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports aes_i]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports aes_o]
set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVCMOS33} [get_ports clk_aud_o]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports wclk_o]
set_property PACKAGE_PIN G22 [get_ports f_si_a_clk3_p]
set_property PACKAGE_PIN F23 [get_ports f_si_a_clk3_n]
######################################################################
## DCI CASCADE MIG
######################################################################
set_property DCI_CASCADE {32 34} [get_iobanks 33]
######################################################################
## Keeping hierarchy DRU
######################################################################
set_property KEEP_HIERARCHY true [get_cells -hier *NIDRU*]

######################################################################
## Asynchronous data
######################################################################
set_property ASYNC_REG true [get_cells -hier -filter name=~*d1_cdc_to*]
set_property ASYNC_REG true [get_cells -hier -filter name=~*_d2*]
set_property ASYNC_REG true [get_cells -hier -filter name=~*_d3*]
#
set_property SHREG_EXTRACT NO [get_cells -hier -filter name=~*d1_cdc_to*]
set_property SHREG_EXTRACT NO [get_cells -hier -filter name=~*_d2*]
set_property SHREG_EXTRACT NO [get_cells -hier -filter name=~*_d3*]

#
set_property ASYNC_REG true [get_cells -hier -filter {name=~*tof_gen_a_ins/tof_reg[*]}]
set_property SHREG_EXTRACT NO [get_cells -hier -filter {name=~*tof_gen_a_ins/tof_reg[*]}]
#
set_property ASYNC_REG true [get_cells -hier -filter name=~*_ss*]
set_property SHREG_EXTRACT NO [get_cells -hier -filter name=~*_ss*]

## tp
#set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS33} [get_ports {tst_o[0]}]
#set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33} [get_ports {tst_o[1]}]
#set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33} [get_ports {tst_o[2]}]
#set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33} [get_ports {tst_o[3]}]
#set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33} [get_ports {tst_i[0]}]
#set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33} [get_ports {tst_i[1]}]
#set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33} [get_ports {tst_o[0]}]
#set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33} [get_ports {tst_o[1]}]

set_property CFGBVS VCCO [current_design]









####################################################################################
# Constraints from file : 'debug_ila.xdc'
####################################################################################






# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
